# Lines configured by Zodium Project ( dont edit , use ~/.zshrc to configure)

# Plugins
if [[ -r /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] &&
   [[ -z "$DISABLE_ZSH_AUTOSUGGESTIONS" ]]; then
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [[ -r /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] &&
   [[ -z "$DISABLE_ZSH_SYNTAX_HIGHLIGHTING" ]]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi